export const randomIssues = [
  'Update .clang-format',
  'Remove Intel unavailable hardware from SDIO IDs',
  'Improve readability of socket err',
  'fix "unsigned" warn when running independently',
  'Add support for USB modems using Conexant CX06836',
  'Integration/soundwire latest',
  'Added SPI0 to Board',
  'Use kvzalloc to make your code better',
  'Fixed bug where "yes" and "no" are mixed up',
  'Rename README to README.md',
  'Typo in qnx6.txt',
  'Update namespace.rst',
  'Fix POSIX: POSIX too slow, Complete performance Overhaul',
  'fix the kernel',
  'Devrezz',
  'Support hard drives that do not implement the Synchronize Cache SCSI command',
  'correct naming lockdown_read arg',
  'Update llc_station.c',
  'gen_initramfs_list.sh is a bash script that isn`t posix compliant.',
  'ab-b5ze-s3 months start from 1 not 0',
  'Confusion of control 2 register contents',
  'Updated nf_conntrack_sip, nf_nat_sip.c modules` creator email',
  'making it more modern',
  '[netfilter]: Fix skb->csum calculation when netfilter manipulation for NF_NAT_MANIP_SRCDST is done on IPV6 packet.',
  'Added rtl8188eus realtek wireless driver files',
  'Linux Commands',
  'Minor grammatical changes to multiqueue.txt',
  'Added colon',
  'Quote to prevent globbing and word splitting',
  'Update dns_resolver-type.h',
  'From Mourya2',
  'A small demo from mourya',
  'created pizza',
  'Bionic develop',
];
